### ISSUE TITLE
2022 Docs Refresh Checklist

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/documentation#154]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Docs sections assignments, please comment with PRs and check off when completed:

- [x] DIY - @kn0wmad 
- [x] Initial Setup complete rework - @gStart9 
- [x] Upgrade from 02x rework - @gStart9
- [x] User Manual Part 1 - @kn0wmad 
- [x] User Manual Part 2 - @gStart9 
- [x] Support - @gStart9 
- [x] Learn - Doc
- [x] Contribute - @kn0wmad 
- [x] Dev Docs - @islandbitcoin @MattDHill @kn0wmad 
- [x] About - @kn0wmad 

### Describe the Use Case

n/a

**Comment by elvece** [comment]
I should no longer be lead on this for developer docs, if possible. I am happy to review them, but someone from the service packaging team should lead the refresh.

**Comment by kn0wmad** [comment]
> I should no longer be lead on this for developer docs, if possible. I am happy to review them, but someone from the service packaging team should lead the refresh.

Updated

**Comment by kn0wmad** [comment]
Closing as complete
